import { SPARKLE_STAGES } from "./config";
import { canUnlockRegionalHall, getCurrentVenue } from "./song-live";
import type { BattleCategory, OriginalSong, Performance, ProducerGameState, RivalBattleRecord } from "./types";
import { getActiveMembers } from "./formation";

const categories: BattleCategory[] = ["vocal", "dance", "song", "character"];
export const calculateBattleStats = (game: ProducerGameState, song: OriginalSong) => {
  const members = getActiveMembers(game);
  const average = (keys: ("vocal" | "harmony" | "dance" | "character" | "lyrics" | "composition" | "choreography")[]) => Math.round(members.reduce((total, member) => total + keys.reduce((sum, key) => sum + member.abilities[key], 0), 0) / Math.max(1, members.length));
  return { vocal: average(["vocal", "harmony"]) + Math.round((song.songStats.vocal + song.songStats.harmony) / 2), dance: average(["dance", "choreography"]) + Math.round((song.songStats.dance + song.songStats.choreography) / 2), song: average(["lyrics", "composition"]) + Math.round((song.songStats.lyrics + song.songStats.composition) / 2), character: average(["character"]) + song.songStats.character };
};
export const compareBattleCategory = (player: number, rival: number) => player > rival ? "WIN" : player < rival ? "LOSE" : "DRAW";
export const applySongAffinityToBattleStats = (stats: Record<BattleCategory, number>, song: OriginalSong) => song.songType === "VOCAL" ? { ...stats, vocal: Math.round(stats.vocal * 1.07) } : song.songType === "DANCE" ? { ...stats, dance: Math.round(stats.dance * 1.08) } : song.songType === "PERFORMANCE" ? { ...stats, character: Math.round(stats.character * 1.08), vocal: Math.round(stats.vocal * 1.04) } : stats;
export const calculateRivalBattleResult = (player: Record<BattleCategory, number>, stage = 1) => { const rival = SPARKLE_STAGES[stage - 1].stats; const categoryResults = Object.fromEntries(categories.map((category) => [category, compareBattleCategory(player[category], rival[category])])) as RivalBattleRecord["categoryResults"]; const wins = categories.filter((category) => categoryResults[category] === "WIN").length; return { categoryResults, overallResult: wins === 4 ? "PERFECT WIN" as const : wins === 3 ? "WIN" as const : wins === 2 ? "DRAW" as const : "Sparkle WIN" as const }; };
export const getBattleImprovementHint = (player: Record<BattleCategory, number>) => { const rival = SPARKLE_STAGES[0].stats; const weakest = categories.filter((category) => player[category] <= rival[category]).sort((a, b) => (rival[a] - player[a]) - (rival[b] - player[b]))[0]; if (!weakest) return "Sparkleをリードしているよ！"; const labels = { vocal: "歌唱", dance: "ダンス", song: "楽曲", character: "キャラ" }; return `あと${rival[weakest] - player[weakest] + 1}でSparkleを逆転！ ${labels[weakest]}が得意なリナをレッスンしよう`; };
export const canStartRivalBattle = (game: ProducerGameState, performances: Performance[]) => getActiveMembers(game).length >= SPARKLE_STAGES[0].requiredMembers && game.songs.filter((song) => song.status === "completed").length >= SPARKLE_STAGES[0].requiredSongs && getCurrentVenue(game, performances).id === SPARKLE_STAGES[0].requiredVenueId;
export const canStartSparkleStage2 = (game: ProducerGameState, performances: Performance[]) => Boolean(game.wonRivalBattleIds?.includes("sparkle-stage-1")) && canUnlockRegionalHall(game) && game.songs.some((song) => song.id === "colorful-memory" && song.status === "completed") && performances.some((performance) => performance.venueId === "regional-hall");
export const getSongRecommendation = (game: ProducerGameState) => { const current = game.songs.filter((song) => song.status === "completed"); const scored = current.map((song) => ({ song, score: Object.values(applySongAffinityToBattleStats(calculateBattleStats(game, song), song)).reduce((total, value) => total + value, 0) })); const best = scored.sort((a, b) => b.score - a.score)[0]; return best ? `${best.song.title}に変えると強くなりそう！` : "完成した曲を選ぼう"; };
export const getRivalBattleRewards = (overallResult: RivalBattleRecord["overallResult"], alreadyWon: boolean, alreadyParticipated = false, stage = 1) => { const reward = SPARKLE_STAGES[stage - 1].rewards; if (overallResult === "PERFECT WIN" || overallResult === "WIN") return alreadyWon ? { fans: 0, points: 0, event: 0 } : { fans: reward.winFans, points: reward.winPoints, event: 1 }; return alreadyParticipated ? { fans: 0, points: 0, event: 0 } : { fans: reward.participationFans, points: reward.participationPoints, event: 0 }; };
