import { NOVA_STAGE_1, SPARKLE_STAGES } from "./config";
import { canUnlockCityHall, canUnlockRegionalHall, getCurrentVenue } from "./song-live";
import type { BattleCategory, OriginalSong, Performance, ProducerGameState, RivalBattleRecord } from "./types";
import { getActiveMembers } from "./formation";

export const battleCategories: BattleCategory[] = ["vocal", "dance", "song", "character"];
export type BattleStats = Record<BattleCategory, number>;
export const calculateBattleStats = (game: ProducerGameState, song: OriginalSong) => {
  const members = getActiveMembers(game);
  const average = (keys: ("vocal" | "harmony" | "dance" | "character" | "lyrics" | "composition" | "choreography")[]) => Math.round(members.reduce((total, member) => total + keys.reduce((sum, key) => sum + member.abilities[key], 0), 0) / Math.max(1, members.length));
  return { vocal: average(["vocal", "harmony"]) + Math.round((song.songStats.vocal + song.songStats.harmony) / 2), dance: average(["dance", "choreography"]) + Math.round((song.songStats.dance + song.songStats.choreography) / 2), song: average(["lyrics", "composition"]) + Math.round((song.songStats.lyrics + song.songStats.composition) / 2), character: average(["character"]) + song.songStats.character };
};
export const compareBattleCategory = (player: number, rival: number) => player > rival ? "WIN" : player < rival ? "LOSE" : "DRAW";
export const getSongAffinityModifiers = (song: OriginalSong): Partial<Record<BattleCategory, number>> => song.songType === "VOCAL" || song.songType === "MESSAGE" ? { vocal: 7, song: 5 } : song.songType === "DANCE" ? { dance: 8 } : song.songType === "PERFORMANCE" ? { character: 8, vocal: 4 } : song.songType === "HARMONY" ? { song: 8, vocal: 5 } : {};
export const applySongAffinityToBattleStats = (stats: BattleStats, song: OriginalSong): BattleStats => Object.entries(getSongAffinityModifiers(song)).reduce((result, [category, percent]) => ({ ...result, [category]: Math.round(result[category as BattleCategory] * (1 + Number(percent) / 100)) }), stats);
export const calculateRivalBattleResult = (player: BattleStats, stage = 1, rivalStats?: BattleStats) => { const rival = rivalStats ?? SPARKLE_STAGES[stage - 1].stats; const categoryResults = Object.fromEntries(battleCategories.map((category) => [category, compareBattleCategory(player[category], rival[category])])) as RivalBattleRecord["categoryResults"]; const wins = battleCategories.filter((category) => categoryResults[category] === "WIN").length; return { categoryResults, overallResult: wins === 4 ? "PERFECT WIN" as const : wins === 3 ? "WIN" as const : wins === 2 ? "DRAW" as const : rival === NOVA_STAGE_1.stats ? "NOVA WIN" as const : "Sparkle WIN" as const }; };
export const getBattleImprovementHint = (player: BattleStats, rival: BattleStats = SPARKLE_STAGES[0].stats, rivalName = "Sparkle") => { const weakest = battleCategories.filter((category) => player[category] <= rival[category]).sort((a, b) => (rival[a] - player[a]) - (rival[b] - player[b]))[0]; if (!weakest) return `${rivalName}をリードしているよ！`; const labels = { vocal: "歌唱", dance: "ダンス", song: "楽曲", character: "キャラ" }; return `あと${rival[weakest] - player[weakest] + 1}で${rivalName}を逆転！ ${labels[weakest]}を育てよう`; };
export const canStartRivalBattle = (game: ProducerGameState, performances: Performance[]) => getActiveMembers(game).length >= SPARKLE_STAGES[0].requiredMembers && game.songs.filter((song) => song.status === "completed").length >= SPARKLE_STAGES[0].requiredSongs && getCurrentVenue(game, performances).id === SPARKLE_STAGES[0].requiredVenueId;
export const canStartSparkleStage2 = (game: ProducerGameState, performances: Performance[]) => Boolean(game.wonRivalBattleIds?.includes("sparkle-stage-1")) && canUnlockRegionalHall(game) && game.songs.some((song) => song.id === "colorful-memory" && song.status === "completed") && performances.some((performance) => performance.venueId === "regional-hall");
export const canStartNovaStage1 = (game: ProducerGameState, performances: Performance[]) => Boolean(game.wonRivalBattleIds?.includes("sparkle-stage-2")) && canUnlockCityHall(game) && game.songs.some((song) => song.id === "tsunagaru-melody" && song.status === "completed") && performances.some((performance) => performance.venueId === "city-hall");
export const simulateRivalBattle = (game: ProducerGameState, song: OriginalSong, rivalStats: BattleStats = NOVA_STAGE_1.stats) => calculateRivalBattleResult(applySongAffinityToBattleStats(calculateBattleStats(game, song), song), 1, rivalStats);
const score = (result: ReturnType<typeof simulateRivalBattle>) => battleCategories.filter((category) => result.categoryResults[category] === "WIN").length;
export const getSongRecommendation = (game: ProducerGameState, currentSong?: OriginalSong) => { const completed = game.songs.filter((song) => song.status === "completed"); const current = currentSong ?? completed[0]; if (!current) return null; const now = simulateRivalBattle(game, current); const best = completed.map((song) => ({ song, result: simulateRivalBattle(game, song) })).sort((a, b) => score(b.result) - score(a.result))[0]; return best && best.song.id !== current.id && score(best.result) > score(now) ? `「${best.song.title}」にすると楽曲で逆転！` : null; };
export const getLeaderRecommendationForBattle = (game: ProducerGameState, song: OriginalSong) => { const active = getActiveMembers(game); const current = simulateRivalBattle(game, song); const best = active.map((member) => ({ member, result: simulateRivalBattle({ ...game, leaderMemberId: member.id }, song) })).sort((a, b) => score(b.result) - score(a.result))[0]; return best && best.member.id !== game.leaderMemberId && score(best.result) > score(current) ? `${best.member.name}をLeaderにするとWINできます！` : null; };
export const getFormationSwapRecommendation = (game: ProducerGameState, song: OriginalSong) => { const current = simulateRivalBattle(game, song); const active = getActiveMembers(game); const inactive = game.members.filter((member) => member.joined && !active.some((item) => item.id === member.id)); for (const replacement of inactive) for (const outgoing of active.filter((member) => member.id !== game.leaderMemberId)) { const result = simulateRivalBattle({ ...game, activeMemberIds: active.map((member) => member.id === outgoing.id ? replacement.id : member.id) }, song); if (score(result) > score(current)) return `${replacement.name}を${outgoing.name}と交代すると${score(current)}勝 → ${score(result)}勝！${score(result) >= 3 ? " WINできます！" : ""}`; } return null; };
export const getTrainingRecommendation = (player: BattleStats, rival: BattleStats = NOVA_STAGE_1.stats) => { const weakest = battleCategories.filter((category) => player[category] <= rival[category]).sort((_, b) => rival[b] - player[b])[0]; return weakest === "vocal" ? "おすすめ育成：歌唱 / ハモリ" : weakest === "dance" ? "おすすめ育成：ダンス / 振付" : weakest === "song" ? "おすすめ育成：作詞 / 作曲" : "おすすめ育成：キャラ"; };
export const getBestBattleRecommendation = (game: ProducerGameState, song: OriginalSong) => getSongRecommendation(game, song) ?? getLeaderRecommendationForBattle(game, song) ?? getFormationSwapRecommendation(game, song) ?? getTrainingRecommendation(applySongAffinityToBattleStats(calculateBattleStats(game, song), song));
export const getRivalBattleRewards = (overallResult: RivalBattleRecord["overallResult"], alreadyWon: boolean, alreadyParticipated = false, stage = 1, rivalId = "sparkle") => { const reward = rivalId === "nova" ? NOVA_STAGE_1.rewards : SPARKLE_STAGES[stage - 1].rewards; if (overallResult === "PERFECT WIN" || overallResult === "WIN") return alreadyWon ? { fans: 0, points: 0, event: 0 } : { fans: reward.winFans, points: reward.winPoints, event: 1 }; return alreadyParticipated ? { fans: 0, points: 0, event: 0 } : { fans: reward.participationFans, points: reward.participationPoints, event: 0 }; };
