import { useMemo, useState } from "react";
import { GACHA_EXCHANGE_LINEUP, TRAINING_ITEMS } from "../../game/gacha/config";
import type { GachaDraw, GachaExchangeDefinition, GachaState } from "../../game/gacha/types";
import { MEMBER_DEFINITIONS } from "../../game/config";
import type { IdolAbility, ProducerGameState } from "../../game/types";

const abilityLabel: Record<IdolAbility, string> = { vocal: "歌唱", harmony: "ハモリ", dance: "ダンス", character: "キャラ", lyrics: "作詞", composition: "作曲", choreography: "振付" };
const rarityLabel = (rarity?: string, source?: string) => source === "starter" ? "STARTER" : rarity ?? "STARTER";
const drawResult = (draw: GachaDraw) => draw.resultType === "member" ? MEMBER_DEFINITIONS.find((member) => member.id === draw.memberId)?.name ?? draw.memberId : TRAINING_ITEMS.find((item) => item.id === draw.itemId)?.name ?? draw.itemId;

export function GachaCollection({ game, gacha, history, onExchange }: { game: ProducerGameState; gacha: GachaState; history: GachaDraw[]; onExchange: (exchange: GachaExchangeDefinition) => void }) {
  const [filter, setFilter] = useState("ALL");
  const [ability, setAbility] = useState<IdolAbility>("dance");
  const members = useMemo(() => MEMBER_DEFINITIONS.filter((member) => filter === "ALL" || rarityLabel(member.rarity, member.sourceType) === filter), [filter]);
  const gold = GACHA_EXCHANGE_LINEUP.find((exchange) => exchange.id === "gold-ticket")!;
  const item = GACHA_EXCHANGE_LINEUP.find((exchange) => exchange.id === `${ability}-item-r`)!;
  return <>
    <section className="rounded-2xl border border-violet-200 bg-violet-50 p-5 shadow-sm"><h3 className="font-black text-lg">スターのかけら交換所</h3><p className="mt-1 text-sm text-violet-800">所持：<b>{gacha.starFragments}</b> 個</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-3"><b>{gold.name}</b><p className="text-xs text-slate-600">{gold.description} / {gold.fragmentCost}個</p><button disabled={gacha.starFragments < gold.fragmentCost} onClick={() => onExchange(gold)} className="mt-2 rounded-lg bg-violet-600 px-3 py-2 text-sm font-bold text-white disabled:bg-slate-300">交換する</button></div><div className="rounded-xl bg-white p-3"><b>R育成アイテム</b><select value={ability} onChange={(event) => setAbility(event.target.value as IdolAbility)} className="ml-2 rounded border p-1 text-sm">{(Object.keys(abilityLabel) as IdolAbility[]).map((key) => <option key={key} value={key}>{abilityLabel[key]}</option>)}</select><p className="mt-1 text-xs text-slate-600">{item.name} +{TRAINING_ITEMS.find((candidate) => candidate.id === item.reward.itemId)?.bonus} / {item.fragmentCost}個</p><button disabled={gacha.starFragments < item.fragmentCost} onClick={() => onExchange(item)} className="mt-2 rounded-lg bg-violet-600 px-3 py-2 text-sm font-bold text-white disabled:bg-slate-300">交換する</button></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black text-lg">ガチャ履歴</h3>{history.length ? <div className="mt-3 space-y-2">{history.slice(0, 10).map((draw) => <div key={draw.drawId} className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span><b>{draw.rarity}</b> {drawResult(draw)} {draw.duplicate && "DUPLICATE"}</span><span>{draw.duplicate ? `かけら +${draw.starFragmentsGained}` : draw.ticketType}</span></div>)}</div> : <p className="mt-2 text-sm text-slate-500">まだガチャ履歴はありません。</p>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><h3 className="mr-2 font-black text-lg">アイドル図鑑 16人</h3>{["ALL", "STARTER", "R", "SR", "SSR"].map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-1 text-xs font-bold ${filter === value ? "bg-fuchsia-600 text-white" : "bg-slate-100 text-slate-600"}`}>{value}</button>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{members.map((definition) => { const owned = game.members.find((member) => member.id === definition.id && member.joined); return <div key={definition.id} className={`rounded-xl border p-3 ${owned ? "border-emerald-200 bg-emerald-50" : "border-slate-200 bg-slate-50"}`}><p className="text-xs font-bold text-violet-700">{rarityLabel(definition.rarity, definition.sourceType)}</p><b>{definition.name}</b><p className="mt-1 text-xs font-bold">{owned ? "OWNED" : "LOCKED"}</p>{owned && <p className="mt-1 text-xs text-slate-700">歌 {owned.abilities.vocal} / ダ {owned.abilities.dance} / キャ {owned.abilities.character}</p>}<p className="mt-1 text-[11px] text-slate-600">Leader: {definition.leaderSkill.name}</p></div>; })}</div><a href="#formation" className="mt-3 inline-block rounded-xl border border-fuchsia-300 px-4 py-2 text-sm font-bold text-fuchsia-700">編成画面へ</a></section>
  </>;
}
