import { useState } from "react";
import { GACHA_CATEGORY_RATES, GACHA_RATES, TRAINING_ITEMS } from "../../game/gacha/config";
import type { GachaDraw, GachaState, GachaTicketType } from "../../game/gacha/types";
import type { ProducerGameState } from "../../game/types";

const labels: Record<GachaTicketType, string> = { normal: "NORMAL", silver: "SILVER", gold: "GOLD", premium: "PREMIUM" };
export function GachaPanel({ game, gacha, forecast, lastDraw, onDraw, onUseItem }: { game: ProducerGameState; gacha: GachaState; forecast: { currentPercent: number; minutesToNext: number; nextPercent: number | null }; lastDraw: GachaDraw | null; onDraw: (type: GachaTicketType) => void; onUseItem: (itemId: string, memberId: string) => void }) {
  const [showRates, setShowRates] = useState(false); const [selectedMember, setSelectedMember] = useState(game.leaderMemberId ?? game.members.find((member) => member.joined)?.id ?? "");
  return <section className="rounded-2xl bg-gradient-to-br from-amber-50 to-violet-50 border border-amber-200 p-5 shadow-sm"><h3 className="font-black text-lg">学習ガチャ</h3><p className="mt-2 font-bold text-violet-800">今週のガチャ予報：{forecast.currentPercent}%</p><p className="text-sm text-slate-600">{forecast.nextPercent === null ? "PREMIUM達成！ 今週のガチャランクはMAX" : `あと${forecast.minutesToNext}分で${forecast.nextPercent >= 120 ? "PREMIUM" : forecast.nextPercent >= 100 ? "GOLD" : forecast.nextPercent >= 90 ? "SILVER" : "NORMAL"}ガチャ！`}</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">{(Object.keys(labels) as GachaTicketType[]).map((type) => <div key={type} className="rounded-xl bg-white p-3"><b>{labels[type]}</b><p>×{gacha.ticketBalances[type]}</p><button disabled={gacha.ticketBalances[type] < 1} onClick={() => onDraw(type)} className="mt-2 rounded-lg bg-violet-600 disabled:bg-slate-300 text-white px-3 py-1 text-sm font-bold">1回引く</button></div>)}</div><button onClick={() => setShowRates((value) => !value)} className="mt-3 text-sm font-bold text-violet-700">{showRates ? "排出率を閉じる" : "排出率を見る"}</button>{showRates && <div className="mt-2 grid sm:grid-cols-2 gap-2 text-xs">{(Object.keys(labels) as GachaTicketType[]).map((type) => <p key={type} className="rounded-lg bg-white p-2"><b>{labels[type]}</b> N {GACHA_RATES[type].N}% / R {GACHA_RATES[type].R}% / SR {GACHA_RATES[type].SR}% / SSR {GACHA_RATES[type].SSR}%<br />R以上: メンバー {GACHA_CATEGORY_RATES.R.member}%・アイテム {GACHA_CATEGORY_RATES.R.item}%</p>)}</div>}<p className="mt-3 text-sm">スターのかけら：<b>{gacha.starFragments}</b>（次回アップデートで交換に使えます）</p>{lastDraw && <div className="mt-3 rounded-xl bg-white p-3"><b>{lastDraw.rarity} {lastDraw.duplicate ? "DUPLICATE" : "NEW!"}</b><p>{lastDraw.resultType === "member" ? lastDraw.memberId : `${TRAINING_ITEMS.find((item) => item.id === lastDraw.itemId)?.name ?? "アイテム"} +${lastDraw.itemId ? TRAINING_ITEMS.find((item) => item.id === lastDraw.itemId)?.bonus : ""}`}{lastDraw.duplicate && `／スターのかけら +${lastDraw.starFragmentsGained}`}</p></div>}<div className="mt-4 border-t pt-3"><b>アイテム</b><select value={selectedMember} onChange={(event) => setSelectedMember(event.target.value)} className="ml-2 rounded border p-1 text-sm">{game.members.filter((member) => member.joined).map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select><div className="grid sm:grid-cols-2 gap-2 mt-2">{TRAINING_ITEMS.filter((item) => (gacha.itemInventory[item.id] ?? 0) > 0).map((item) => <div key={item.id} className="rounded-lg bg-white p-2 text-sm"><b>{item.name} {item.rarity}</b> ×{gacha.itemInventory[item.id]}<p>{item.ability} +{item.bonus}</p><button onClick={() => onUseItem(item.id, selectedMember)} className="rounded bg-amber-500 text-white px-3 py-1 font-bold">使う</button></div>)}</div></div></section>;
}
