import { Music, Sparkles, Trophy, Users } from "lucide-react";
import { LESSON_COST, LIVE_COST, MEMBER_JOIN_COST, RIVAL_NAME, SPARKLE_STAGES, THIRD_MEMBER_JOIN_COST, VENUES } from "../../game/config";
import { getRivalBattle, getTokyoDomeMissions } from "../../game/progression";
import { canJoinMember, canLesson, canRecruitThirdMember } from "../../game/rewards";
import type { ProducerGameState } from "../../game/types";
import type { WeeklyResult } from "../../game/types";
import type { Performance, RivalBattleRecord } from "../../game/types";
import { calculateBattleStats, canStartRivalBattle, getBattleImprovementHint } from "../../game/rival-battle";
import { canCreateSong, canPerformLive, getCurrentVenue, getNextGoal, isVenueSoldOut } from "../../game/song-live";

const time = (minutes: number) => `${Math.floor(minutes / 60)}時間${minutes % 60}分`;

export function ProducerHome({ game, weeklyMinutes, weeklyGoalMinutes, onClaim, claimablePoints, claimableBasePoints, onLesson, onJoin, boostPercent, weeklyResults, performances, rivalBattles, onCreateSong, onPerform, onRivalBattle }: { game: ProducerGameState; weeklyMinutes: number; weeklyGoalMinutes: number; claimablePoints: number; claimableBasePoints: number; onClaim: () => void; onLesson: (memberId: string) => void; onJoin: () => void; boostPercent: number; weeklyResults: WeeklyResult[]; performances: Performance[]; rivalBattles: RivalBattleRecord[]; onCreateSong: (songId: string) => void; onPerform: () => void; onRivalBattle: (songId: string) => void }) {
  const battle = getRivalBattle(weeklyMinutes, weeklyGoalMinutes);
  const missions = getTokyoDomeMissions(game, weeklyMinutes / weeklyGoalMinutes);
  const member = game.members.find((m) => m.id === "science" && m.joined) ?? game.members.find((m) => m.joined)!;
  const song = game.songs[0]; const battleSong = game.songs[1]?.status === "completed" ? game.songs[1] : song; const latestRival = rivalBattles[0]; const playerStats = battleSong.status === "completed" ? calculateBattleStats(game, battleSong) : null; const hint = playerStats ? getBattleImprovementHint(playerStats) : undefined; const nextGoal = getNextGoal(game, performances, latestRival?.overallResult, hint); const nextVenue = VENUES[1]; const currentVenue = getCurrentVenue(game, performances); const canThird = canRecruitThirdMember(game, performances.length > 0); const canBattle = battleSong.status === "completed" && canStartRivalBattle(game, performances);
  return <div className="w-full max-w-5xl mx-auto px-4 md:px-8 py-5 space-y-5 text-slate-800">
    <section className="rounded-3xl bg-gradient-to-br from-fuchsia-500 via-violet-500 to-indigo-600 text-white p-6 shadow-lg">
      <div className="flex items-center gap-2 text-fuchsia-100 font-bold"><Sparkles className="w-5 h-5" />アイドルプロデュース</div>
      <h2 className="text-2xl font-black mt-2">きみは4人組アイドルのプロデューサー！</h2>
      <p className="mt-2 text-sm text-indigo-100">勉強して活動ポイントを集め、いつか東京ドームを満員にしよう。</p>
    </section>
    <section className="grid md:grid-cols-3 gap-4">
      <div className="rounded-2xl bg-amber-50 border border-amber-200 p-5"><div className="flex gap-2 font-bold text-amber-800"><Sparkles />活動ポイント</div><p className="text-3xl font-black mt-2">{game.activityPoints} P</p>{claimablePoints > 0 ? <><button onClick={onClaim} className="mt-3 rounded-xl bg-amber-500 text-white px-4 py-2 font-bold">学習分 +{claimablePoints}P を受け取る</button>{claimablePoints > claimableBasePoints && <p className="mt-1 text-xs text-amber-800">基本 +{claimableBasePoints}P ／テストBONUS +{claimablePoints - claimableBasePoints}P</p>}</> : <p className="mt-3 text-sm text-amber-700">あと10分の学習で1P！</p>}</div>
      <div className="rounded-2xl bg-pink-50 border border-pink-200 p-5"><div className="flex gap-2 font-bold text-pink-800"><Users />ファン</div><p className="text-3xl font-black mt-2">{game.fans.toLocaleString()} 人</p><p className="mt-3 text-sm text-pink-700">次のライブ会場まであと {Math.max(0, nextVenue.requiredFans - game.fans).toLocaleString()} 人</p></div>
      <div className="rounded-2xl bg-sky-50 border border-sky-200 p-5"><div className="flex gap-2 font-bold text-sky-800"><Trophy />東京ドーム</div><p className="text-3xl font-black mt-2">{missions.filter((m) => m.done).length}/7</p><p className="mt-3 text-sm text-sky-700">7つの夢ミッションを進めよう</p></div>
    </section>
    {boostPercent > 0 && <section className="rounded-2xl bg-violet-50 border border-violet-200 p-4"><p className="font-black text-violet-800">プロデューサーブースト +{boostPercent}%</p><p className="text-sm text-violet-700 mt-1">テストで伸びた力が、学習でもらえる活動ポイントをUP！端数も次回へ繰り越されます。</p></section>}
    <section className="rounded-2xl bg-indigo-600 text-white p-5 shadow-sm"><p className="text-xs font-bold text-indigo-200">NEXT GOAL</p><p className="mt-1 text-xl font-black">{nextGoal}</p></section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">今週のプロデュースバトル</h3><div className="grid sm:grid-cols-3 gap-3 mt-3"><div><p className="text-xs text-slate-500">MY IDOL</p><p className="font-black text-xl">{time(weeklyMinutes)}</p></div><div><p className="text-xs text-slate-500">今週の目標</p><p className="font-black text-xl">{time(weeklyGoalMinutes)}</p></div><div><p className="text-xs text-slate-500">{RIVAL_NAME}に勝つには</p><p className="font-black text-xl text-violet-600">あと{time(battle.remaining)}！</p></div></div><p className="mt-4 font-bold text-sm">{battle.status}：{battle.message}（勝てばファン +120人）</p></section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><div className="flex items-center gap-2"><Music className="text-violet-600" /><h3 className="font-black text-lg">{member.name}のレッスン</h3></div><p className="text-sm text-slate-500 mt-1">得意：{member.specialty}</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4">{Object.entries(member.abilities).slice(0, 4).map(([ability, value]) => <div key={ability} className="bg-slate-50 rounded-xl p-3 text-center"><p className="text-xs text-slate-500">{({ vocal: "歌唱", harmony: "ハモリ", dance: "ダンス", character: "キャラ" } as Record<string,string>)[ability] ?? ability}</p><p className="font-black text-xl">{value}</p></div>)}</div><button disabled={!canLesson(game)} onClick={() => onLesson(member.id)} className="mt-4 rounded-xl bg-violet-600 disabled:bg-slate-300 text-white px-5 py-3 font-bold">{member.id === "science" ? "ダンス" : "歌唱"}レッスン（{LESSON_COST}P）</button><p className="mt-2 text-xs text-slate-500">レッスンで得意な能力 +2。能力は下がりません。</p></section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">メンバーを集めよう</h3><div className="grid sm:grid-cols-3 gap-2 mt-3">{game.members.filter((m) => !m.joined).map((m, index) => <div key={m.id} className="rounded-xl bg-slate-50 p-3"><p className="font-bold">{m.name}</p><p className="text-xs text-slate-500">{m.id === "science" ? "初ライブ後に加入" : index === 0 ? `あと${Math.max(0, MEMBER_JOIN_COST - game.activityPoints)}Pで加入` : "LOCKED・これから解放"}</p></div>)}</div>{(canJoinMember(game) || canThird) && <button onClick={onJoin} className="mt-3 rounded-xl bg-fuchsia-600 text-white px-5 py-3 font-bold">新メンバーを迎える（{canThird ? THIRD_MEMBER_JOIN_COST : MEMBER_JOIN_COST}P）</button>}</section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">オリジナル曲</h3>{game.songs.map((item) => <div key={item.id} className="mt-2 rounded-xl bg-slate-50 p-3"><p className="font-bold">🎵 {item.title} <span className="text-xs text-violet-600">{item.songType}</span></p>{item.status === "completed" ? <p className="text-sm text-emerald-700">完成！ ライブ {item.performanceCount}回</p> : <><p className="text-sm text-slate-500">必要：{item.requiredActivityPoints}P / メンバー {item.requiredMembers}人</p><button disabled={!canCreateSong(game, item, performances)} onClick={() => onCreateSong(item.id)} className="mt-2 rounded-xl bg-indigo-600 disabled:bg-slate-300 text-white px-4 py-2 font-bold">曲を作る</button></>}</div>)}</section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">ライブ</h3><p className="text-sm text-slate-600">{currentVenue.name} / {currentVenue.capacity}席</p><button disabled={!canPerformLive(game, song, currentVenue.id)} onClick={onPerform} className="mt-3 rounded-xl bg-rose-500 disabled:bg-slate-300 text-white px-5 py-3 font-bold">ライブをする（準備 {LIVE_COST}P）</button>{performances.length > 0 && <div className="mt-3 text-sm"><b>ライブ履歴</b>{performances.slice(0, 3).map((performance) => <p key={performance.performanceId}>{performance.audience}/{performance.capacity}人 / ファン +{performance.fanGain}{isVenueSoldOut(performance) && " SOLD OUT!"}</p>)}</div>}<p className="mt-2 font-bold">100席満員：{game.milestones?.miniLiveHouseSoldOut ? "達成！" : "これから"}</p></section>
    <section className="rounded-2xl bg-slate-100 border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">次会場予告：地域ホール（300席）</h3><p>{game.songsCompleted >= 2 ? "✅" : "⬜"} オリジナル曲2曲</p><p>{game.wonRivalBattleIds?.includes("sparkle-stage-1") ? "✅" : "⬜"} Sparkle初対バン勝利</p><p>{game.milestones?.miniLiveHouseSoldOut ? "✅" : "⬜"} ミニライブハウス100席満員</p></section>
    <section className="rounded-2xl bg-fuchsia-50 border border-fuchsia-200 p-5 shadow-sm"><h3 className="font-black text-lg">Sparkleと対バン！</h3>{playerStats && <div className="mt-3 grid grid-cols-2 gap-2 text-sm">{Object.entries(playerStats).map(([key, value]) => <p key={key} className="rounded-lg bg-white p-2">{({ vocal: "歌唱", dance: "ダンス", song: "楽曲", character: "キャラ" } as Record<string, string>)[key]} あなた {value} / Sparkle {SPARKLE_STAGES[0].stats[key as keyof typeof playerStats]}</p>)}</div>}{latestRival && <p className="mt-3 font-black">{latestRival.overallResult}</p>}<p className="mt-2 font-bold text-fuchsia-800">{hint}</p><button disabled={!canBattle} onClick={() => onRivalBattle(battleSong.id)} className="mt-3 rounded-xl bg-fuchsia-600 disabled:bg-slate-300 text-white px-5 py-3 font-bold">Sparkleと対バン</button></section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">東京ドームへの7つの夢ミッション</h3><div className="mt-3 grid md:grid-cols-2 gap-2">{missions.map((mission, index) => <div key={mission.label} className={`rounded-xl px-3 py-2 text-sm font-bold ${mission.done ? "bg-emerald-50 text-emerald-700" : "bg-slate-50 text-slate-600"}`}>{mission.done ? "✓" : "○"} {index + 1}. {mission.label}</div>)}</div></section>
    <section className="rounded-2xl bg-white border border-slate-200 p-5 shadow-sm"><h3 className="font-black text-lg">最近のプロデュース結果</h3>{weeklyResults.length ? <div className="mt-3 space-y-2">{weeklyResults.slice(0, 4).map((result) => <div key={result.weekId} className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{result.weekId} {result.battleResult}</span><b className={result.fanDelta >= 0 ? "text-emerald-600" : "text-rose-600"}>{result.fanDelta >= 0 ? "+" : ""}{result.fanDelta}人</b></div>)}</div> : <p className="mt-2 text-sm text-slate-500">最初の週が終わると、ここに結果が残るよ。</p>}</section>
  </div>;
}
