import { getActiveMembers } from "../formation";
import type { ProducerGameState } from "../types";
import { simulateTourPerformance, type TourSimulation } from "./simulation";
import type { TourStopId } from "./types";

export type TourRecommendation = { type: "song" | "leader" | "formation" | "training"; targetId?: string; predictedAudience: number; audienceGain: number; willClear: boolean; willSoldOut: boolean; messageKey: string };
const better = (current: TourSimulation, candidate: TourSimulation) => candidate.audience > current.audience && (!current.isClear && candidate.isClear || current.isClear && !current.isSoldOut && candidate.isSoldOut || candidate.audience > current.audience);
const candidate = (type: TourRecommendation["type"], current: TourSimulation, next: TourSimulation, targetId?: string): TourRecommendation | null => better(current, next) ? { type, targetId, predictedAudience: next.audience, audienceGain: next.audience - current.audience, willClear: next.isClear, willSoldOut: next.isSoldOut, messageKey: `${type}-${!current.isClear && next.isClear ? "clear" : "improve"}` } : null;
export const getTourSongRecommendation = (game: ProducerGameState, stopId: TourStopId, selectedSongId: string) => { const current = simulateTourPerformance(game, stopId, selectedSongId); if (!current || current.isSoldOut) return null; return game.songs.filter((song) => song.status === "completed" && song.id !== selectedSongId).map((song) => candidate("song", current, simulateTourPerformance(game, stopId, song.id)!, song.id)).filter((value): value is TourRecommendation => !!value).sort((a, b) => Number(b.willClear) - Number(a.willClear) || b.audienceGain - a.audienceGain)[0] ?? null; };
export const getTourLeaderRecommendation = (game: ProducerGameState, stopId: TourStopId, selectedSongId: string) => { const current = simulateTourPerformance(game, stopId, selectedSongId); if (!current || current.isSoldOut) return null; return getActiveMembers(game).filter((member) => member.id !== game.leaderMemberId).map((member) => candidate("leader", current, simulateTourPerformance({ ...game, leaderMemberId: member.id }, stopId, selectedSongId)!, member.id)).filter((value): value is TourRecommendation => !!value).sort((a, b) => Number(b.willClear) - Number(a.willClear) || b.audienceGain - a.audienceGain)[0] ?? null; };
export const getTourFormationRecommendation = (game: ProducerGameState, stopId: TourStopId, selectedSongId: string) => { const current = simulateTourPerformance(game, stopId, selectedSongId); if (!current || current.isSoldOut) return null; const active = getActiveMembers(game); const inactive = game.members.filter((member) => member.joined && !active.some((item) => item.id === member.id)); const options = inactive.flatMap((replacement) => active.filter((outgoing) => outgoing.id !== game.leaderMemberId).map((outgoing) => candidate("formation", current, simulateTourPerformance({ ...game, activeMemberIds: active.map((member) => member.id === outgoing.id ? replacement.id : member.id) }, stopId, selectedSongId)!, `${replacement.id}:${outgoing.id}`))).filter((value): value is TourRecommendation => !!value); return options.sort((a, b) => Number(b.willClear) - Number(a.willClear) || b.audienceGain - a.audienceGain)[0] ?? null; };
export const getTourTrainingRecommendation = (game: ProducerGameState, stopId: TourStopId, selectedSongId: string): TourRecommendation | null => { const current = simulateTourPerformance(game, stopId, selectedSongId); if (!current || current.isClear) return null; const label = stopId === "tour-stop-2" ? "dance-choreography" : stopId === "tour-stop-3" ? "character-dance" : "vocal-harmony"; return { type: "training", targetId: label, predictedAudience: current.audience, audienceGain: 0, willClear: false, willSoldOut: false, messageKey: `training-${label}` }; };
export const getBestTourRecommendation = (game: ProducerGameState, stopId: TourStopId, selectedSongId: string) => { const current = simulateTourPerformance(game, stopId, selectedSongId); if (!current || current.isSoldOut) return null; const options = [getTourSongRecommendation(game, stopId, selectedSongId), getTourLeaderRecommendation(game, stopId, selectedSongId), getTourFormationRecommendation(game, stopId, selectedSongId)].filter((value): value is TourRecommendation => !!value).sort((a, b) => Number(b.willClear) - Number(a.willClear) || Number(b.willSoldOut) - Number(a.willSoldOut) || b.audienceGain - a.audienceGain); return options[0] ?? getTourTrainingRecommendation(game, stopId, selectedSongId); };
